version: "3"

networks:
    icehomedev-net:
        driver: bridge

services:

    icehomedev:
        image: mysql
        restart: always
        tty: true
        ports:
            - "3303:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-database}
            MYSQL_USER: ${MYSQL_USER:-database}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Password}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootPassword}
            SERVICE_TAGS: dev
            SERVICE_NAME: icehomedevdb
        volumes:
            - ./data:/var/lib/mysql
        networks:
            - icehomedev-net

    # redis
    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6339:6379"
        networks:
            - icehomedev-net

    # adminer
    adminer:
        image: adminer
        restart: always
        depends_on:
            - icehomedev
        networks:
            - icehomedev-net
        ports:
            - 6000:8080
        environment:
            ADMINER_DESIGN: "pepa-linha"
            ADMINER_DEFAULT_SERVER: mysql


